"""Dumps a real source bundle for the Stage B report.

Not an assertion of behaviour — the other Phase 4 modules do that. This exists
so the bundle shown in documentation is generated by the code rather than
written by hand, and so it cannot quietly drift away from what is actually sent.
Runs only when SUMMARY_BUNDLE_DUMP names an output file.
"""

import json
import os
import uuid

import pytest

from app.models import Consultation, DoctorProfile
from app.services import case_summary_bundle, consultation_service
from tests.conftest import API, create_problem, process_record, request_consultation

DUMP = os.environ.get("SUMMARY_BUNDLE_DUMP")
pytestmark = pytest.mark.skipif(not DUMP, reason="SUMMARY_BUNDLE_DUMP not set")


def test_dump_example_bundle(client, db, seeded_case):
    patient, doctor = seeded_case.patient, seeded_case.doctor
    client.put(f"{API}/patients/me/ai-consent", json={"granted": True}, headers=patient.h)

    # A Tamil problem the patient confirms facts on.
    problem = create_problem(
        client, patient, text="எனக்கு மூன்று நாட்களாக தலைவலி மற்றும் காய்ச்சல் உள்ளது.", language="ta"
    )
    facts = process_record(client, patient, problem["id"]).json()["facts"]
    for fact in facts[:2]:
        client.post(
            f"{API}/patients/me/ai/facts/{fact['id']}", json={"action": "confirm"}, headers=patient.h
        )

    # An earlier consultation this doctor completed, so a doctor-authored source exists.
    first = request_consultation(client, seeded_case).json()
    client.post(f"{API}/doctors/me/consultations/{first['id']}/accept", headers=doctor.h)
    client.put(
        f"{API}/doctors/me/consultations/{first['id']}/assessment",
        json={"doctor_assessment": "Blood pressure reviewed; advised follow-up in two weeks."},
        headers=doctor.h,
    )
    client.post(f"{API}/doctors/me/consultations/{first['id']}/complete", headers=doctor.h)

    current = client.post(
        f"{API}/patients/me/consultations",
        json={
            "doctor_id": doctor.id,
            "share": {
                "current_problem_ids": [problem["id"]],
                "medical_record_ids": [seeded_case.shared_rec["id"]],
                "document_ids": [seeded_case.shared_doc["id"]],
                "consultation_ids": [],
                "prescription_ids": [],
            },
            "request_message": "Headache for three days, please review my report.",
            "request_language": "en",
        },
        headers=patient.h,
    ).json()

    c = db.get(Consultation, uuid.UUID(current["id"]))
    assert db.get(DoctorProfile, uuid.UUID(doctor.id))
    context = consultation_service.resolve_authorized_context(db, c)
    bundle = case_summary_bundle.build_source_bundle(db, context)

    with open(DUMP, "w", encoding="utf-8") as fh:
        json.dump(
            {
                "provider_payload": bundle.provider_payload(),
                "hash": bundle.hash(),
                "canonical_length": len(bundle.canonical()),
                "resolution_kept_server_side": [i.resolution for i in bundle.items],
                "excluded_unshared": {
                    "record_id": seeded_case.private_rec["id"],
                    "document_id": seeded_case.private_doc["id"],
                },
            },
            fh,
            ensure_ascii=False,
            indent=2,
        )
