"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-12 00:44:01.947718
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('actor_role', sa.String(length=16), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('patient_id', sa.Uuid(), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_actor_user_id'), 'audit_events', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_patient_id'), 'audit_events', ['patient_id'], unique=False)
    op.create_table('users',
    sa.Column('role', sa.Enum('patient', 'doctor', 'admin', name='user_role', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('doctor_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('specialization', sa.String(length=120), nullable=False),
    sa.Column('qualification', sa.String(length=200), nullable=False),
    sa.Column('registration_identifier', sa.String(length=64), nullable=False),
    sa.Column('clinic_name', sa.String(length=200), nullable=True),
    sa.Column('clinic_address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('is_accepting_consultations', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_doctor_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_doctor_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_doctor_profiles_user_id'))
    )
    op.create_index(op.f('ix_doctor_profiles_specialization'), 'doctor_profiles', ['specialization'], unique=False)
    op.create_table('patient_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('sex', sa.Enum('female', 'male', 'other', 'undisclosed', name='sex', native_enum=False, create_constraint=True, length=32), server_default='undisclosed', nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('preferred_language', sa.Enum('en', 'hi', 'ta', 'te', 'kn', 'ml', 'mr', 'bn', 'gu', 'pa', 'or', 'as', name='preferred_language', native_enum=False, create_constraint=True, length=32), server_default='en', nullable=False),
    sa.Column('emergency_contact_name', sa.String(length=120), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=32), nullable=True),
    sa.Column('emergency_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_patient_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patient_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_patient_profiles_user_id'))
    )
    op.create_table('consultations',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('requested', 'accepted', 'active', 'completed', 'cancelled', name='consultation_status', native_enum=False, create_constraint=True, length=32), server_default='requested', nullable=False),
    sa.Column('request_message', sa.Text(), nullable=True),
    sa.Column('request_language', sa.Enum('en', 'hi', 'ta', 'te', 'kn', 'ml', 'mr', 'bn', 'gu', 'pa', 'or', 'as', name='request_language', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('patient_shared_context', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('doctor_assessment', sa.Text(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by_role', sa.Enum('patient', 'doctor', 'admin', name='cancelled_by_role', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_profiles.id'], name=op.f('fk_consultations_doctor_id_doctor_profiles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], name=op.f('fk_consultations_patient_id_patient_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consultations'))
    )
    op.create_index('ix_consultations_doctor_status', 'consultations', ['doctor_id', 'status'], unique=False)
    op.create_index('ix_consultations_patient_status', 'consultations', ['patient_id', 'status'], unique=False)
    op.create_table('doctor_languages',
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('language_code', sa.Enum('en', 'hi', 'ta', 'te', 'kn', 'ml', 'mr', 'bn', 'gu', 'pa', 'or', 'as', name='language_code', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_profiles.id'], name=op.f('fk_doctor_languages_doctor_id_doctor_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('doctor_id', 'language_code', name=op.f('pk_doctor_languages'))
    )
    op.create_table('medical_documents',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('file_name', sa.String(length=160), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_reference', sa.String(length=500), nullable=False),
    sa.Column('document_type', sa.Enum('prescription', 'lab_report', 'discharge_summary', 'scan', 'other', name='document_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('source_language', sa.Enum('en', 'hi', 'ta', 'te', 'kn', 'ml', 'mr', 'bn', 'gu', 'pa', 'or', 'as', name='document_language', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('status', sa.Enum('uploaded', 'processing', 'processed', 'failed', name='document_status', native_enum=False, create_constraint=True, length=32), server_default='uploaded', nullable=False),
    sa.Column('uploaded_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], name=op.f('fk_medical_documents_patient_id_patient_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], name=op.f('fk_medical_documents_uploaded_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medical_documents')),
    sa.UniqueConstraint('storage_reference', name=op.f('uq_medical_documents_storage_reference'))
    )
    op.create_index(op.f('ix_medical_documents_patient_id'), 'medical_documents', ['patient_id'], unique=False)
    op.create_table('medical_records',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('condition', 'allergy', 'medication', 'history_note', 'current_problem', name='record_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), server_default='', nullable=False),
    sa.Column('source', sa.Enum('patient', 'ai_extracted', 'doctor', name='record_source', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('source_language', sa.Enum('en', 'hi', 'ta', 'te', 'kn', 'ml', 'mr', 'bn', 'gu', 'pa', 'or', 'as', name='source_language', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('status', sa.Enum('active', 'resolved', name='record_status', native_enum=False, create_constraint=True, length=32), server_default='active', nullable=False),
    sa.Column('recorded_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], name=op.f('fk_medical_records_patient_id_patient_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], name=op.f('fk_medical_records_recorded_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medical_records'))
    )
    op.create_index('ix_medical_records_patient_type', 'medical_records', ['patient_id', 'type'], unique=False)
    op.create_table('ai_artifacts',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('consultation_id', sa.Uuid(), nullable=True),
    sa.Column('artifact_type', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('source_references', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('input_language', sa.Enum('en', 'hi', 'ta', 'te', 'kn', 'ml', 'mr', 'bn', 'gu', 'pa', 'or', 'as', name='input_language', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('output_language', sa.Enum('en', 'hi', 'ta', 'te', 'kn', 'ml', 'mr', 'bn', 'gu', 'pa', 'or', 'as', name='output_language', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('content', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('review_status', sa.Enum('unreviewed', 'confirmed', 'rejected', name='ai_review_status', native_enum=False, create_constraint=True, length=32), server_default='unreviewed', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], name=op.f('fk_ai_artifacts_consultation_id_consultations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], name=op.f('fk_ai_artifacts_patient_id_patient_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_artifacts'))
    )
    op.create_index('ix_ai_artifacts_patient_type', 'ai_artifacts', ['patient_id', 'artifact_type'], unique=False)
    op.create_table('consultation_messages',
    sa.Column('consultation_id', sa.Uuid(), nullable=False),
    sa.Column('sender_user_id', sa.Uuid(), nullable=True),
    sa.Column('sender_role', sa.Enum('patient', 'doctor', 'admin', name='sender_role', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('language', sa.Enum('en', 'hi', 'ta', 'te', 'kn', 'ml', 'mr', 'bn', 'gu', 'pa', 'or', 'as', name='message_language', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], name=op.f('fk_consultation_messages_consultation_id_consultations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], name=op.f('fk_consultation_messages_sender_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consultation_messages'))
    )
    op.create_index(op.f('ix_consultation_messages_consultation_id'), 'consultation_messages', ['consultation_id'], unique=False)
    op.create_table('consultation_shares',
    sa.Column('consultation_id', sa.Uuid(), nullable=False),
    sa.Column('item_type', sa.Enum('medical_record', 'document', 'consultation', 'prescription', name='share_item_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], name=op.f('fk_consultation_shares_consultation_id_consultations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consultation_shares')),
    sa.UniqueConstraint('consultation_id', 'item_type', 'item_id', name='uq_consultation_share_item')
    )
    op.create_index(op.f('ix_consultation_shares_consultation_id'), 'consultation_shares', ['consultation_id'], unique=False)
    op.create_table('prescriptions',
    sa.Column('consultation_id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], name=op.f('fk_prescriptions_consultation_id_consultations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_profiles.id'], name=op.f('fk_prescriptions_doctor_id_doctor_profiles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], name=op.f('fk_prescriptions_patient_id_patient_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prescriptions'))
    )
    op.create_index(op.f('ix_prescriptions_consultation_id'), 'prescriptions', ['consultation_id'], unique=False)
    op.create_index(op.f('ix_prescriptions_doctor_id'), 'prescriptions', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_prescriptions_patient_id'), 'prescriptions', ['patient_id'], unique=False)
    op.create_table('prescription_items',
    sa.Column('prescription_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('medication', sa.String(length=200), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=False),
    sa.Column('frequency', sa.String(length=100), nullable=False),
    sa.Column('duration', sa.String(length=100), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], name=op.f('fk_prescription_items_prescription_id_prescriptions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prescription_items'))
    )
    op.create_index(op.f('ix_prescription_items_prescription_id'), 'prescription_items', ['prescription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prescription_items_prescription_id'), table_name='prescription_items')
    op.drop_table('prescription_items')
    op.drop_index(op.f('ix_prescriptions_patient_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_doctor_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_consultation_id'), table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index(op.f('ix_consultation_shares_consultation_id'), table_name='consultation_shares')
    op.drop_table('consultation_shares')
    op.drop_index(op.f('ix_consultation_messages_consultation_id'), table_name='consultation_messages')
    op.drop_table('consultation_messages')
    op.drop_index('ix_ai_artifacts_patient_type', table_name='ai_artifacts')
    op.drop_table('ai_artifacts')
    op.drop_index('ix_medical_records_patient_type', table_name='medical_records')
    op.drop_table('medical_records')
    op.drop_index(op.f('ix_medical_documents_patient_id'), table_name='medical_documents')
    op.drop_table('medical_documents')
    op.drop_table('doctor_languages')
    op.drop_index('ix_consultations_patient_status', table_name='consultations')
    op.drop_index('ix_consultations_doctor_status', table_name='consultations')
    op.drop_table('consultations')
    op.drop_table('patient_profiles')
    op.drop_index(op.f('ix_doctor_profiles_specialization'), table_name='doctor_profiles')
    op.drop_table('doctor_profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_audit_events_patient_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_user_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
