"""phase 2 ai foundation

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-12 11:15:29.471775
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_extracted_facts',
    sa.Column('artifact_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('symptom', 'duration', 'medication', 'allergy', 'medical_history', 'measurement', name='fact_category', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('value', sa.String(length=300), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('evidence_quote', sa.Text(), nullable=False),
    sa.Column('evidence_start', sa.Integer(), nullable=True),
    sa.Column('evidence_end', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('validation_status', sa.Enum('validated', 'needs_review', 'unsupported', name='fact_validation', native_enum=False, create_constraint=True, length=32), server_default='needs_review', nullable=False),
    sa.Column('validation_note', sa.String(length=200), nullable=True),
    sa.Column('review_state', sa.Enum('pending', 'confirmed', 'edited', 'rejected', name='fact_review_state', native_enum=False, create_constraint=True, length=32), server_default='pending', nullable=False),
    sa.Column('edited_value', sa.String(length=300), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('medical_record_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['ai_artifacts.id'], name=op.f('fk_ai_extracted_facts_artifact_id_ai_artifacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['medical_record_id'], ['medical_records.id'], name=op.f('fk_ai_extracted_facts_medical_record_id_medical_records'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], name=op.f('fk_ai_extracted_facts_patient_id_patient_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], name=op.f('fk_ai_extracted_facts_reviewed_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_extracted_facts'))
    )
    op.create_index(op.f('ix_ai_extracted_facts_artifact_id'), 'ai_extracted_facts', ['artifact_id'], unique=False)
    op.create_index(op.f('ix_ai_extracted_facts_source_id'), 'ai_extracted_facts', ['source_id'], unique=False)
    op.create_index('ix_ai_facts_patient_state', 'ai_extracted_facts', ['patient_id', 'review_state'], unique=False)
    op.add_column('ai_artifacts', sa.Column('prompt_version', sa.String(length=64), nullable=True))
    op.add_column('ai_artifacts', sa.Column('source_hash', sa.String(length=64), nullable=True))
    op.add_column('ai_artifacts', sa.Column('cache_key', sa.String(length=255), nullable=True))
    op.add_column('ai_artifacts', sa.Column('status', sa.Enum('succeeded', 'failed', 'skipped', name='ai_artifact_status', native_enum=False, create_constraint=True, length=32), server_default='succeeded', nullable=False))
    op.add_column('ai_artifacts', sa.Column('error_code', sa.String(length=64), nullable=True))
    op.add_column('ai_artifacts', sa.Column('latency_ms', sa.Integer(), nullable=True))
    op.add_column('ai_artifacts', sa.Column('input_tokens', sa.Integer(), nullable=True))
    op.add_column('ai_artifacts', sa.Column('output_tokens', sa.Integer(), nullable=True))
    op.add_column('ai_artifacts', sa.Column('estimated_cost_usd', sa.Float(), nullable=True))
    op.create_index('ix_ai_artifacts_cache_key', 'ai_artifacts', ['cache_key'], unique=False)
    op.create_index(op.f('ix_ai_artifacts_source_hash'), 'ai_artifacts', ['source_hash'], unique=False)
    op.add_column('patient_profiles', sa.Column('ai_processing_consent', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('patient_profiles', sa.Column('ai_consent_updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient_profiles', 'ai_consent_updated_at')
    op.drop_column('patient_profiles', 'ai_processing_consent')
    op.drop_index(op.f('ix_ai_artifacts_source_hash'), table_name='ai_artifacts')
    op.drop_index('ix_ai_artifacts_cache_key', table_name='ai_artifacts')
    op.drop_column('ai_artifacts', 'estimated_cost_usd')
    op.drop_column('ai_artifacts', 'output_tokens')
    op.drop_column('ai_artifacts', 'input_tokens')
    op.drop_column('ai_artifacts', 'latency_ms')
    op.drop_column('ai_artifacts', 'error_code')
    op.drop_column('ai_artifacts', 'status')
    op.drop_column('ai_artifacts', 'cache_key')
    op.drop_column('ai_artifacts', 'source_hash')
    op.drop_column('ai_artifacts', 'prompt_version')
    op.drop_index('ix_ai_facts_patient_state', table_name='ai_extracted_facts')
    op.drop_index(op.f('ix_ai_extracted_facts_source_id'), table_name='ai_extracted_facts')
    op.drop_index(op.f('ix_ai_extracted_facts_artifact_id'), table_name='ai_extracted_facts')
    op.drop_table('ai_extracted_facts')
    # ### end Alembic commands ###
