"""phase 3 document intelligence

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-12 13:30:22.696122
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0004'
down_revision: str | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_extractions',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('succeeded', 'partial', 'failed', name='document_extraction_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('source_sha256', sa.String(length=64), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('pages_processed', sa.Integer(), nullable=False),
    sa.Column('truncated', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('methods', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('engines', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('warnings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('requested_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['medical_documents.id'], name=op.f('fk_document_extractions_document_id_medical_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], name=op.f('fk_document_extractions_patient_id_patient_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], name=op.f('fk_document_extractions_requested_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_extractions'))
    )
    op.create_index(op.f('ix_document_extractions_document_id'), 'document_extractions', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_extractions_patient_id'), 'document_extractions', ['patient_id'], unique=False)
    op.create_table('document_pages',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('extraction_id', sa.Uuid(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), server_default='', nullable=False),
    sa.Column('text_sha256', sa.String(length=64), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('engine', sa.String(length=160), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('blocks', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('warnings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('detected_language', sa.Enum('en', 'hi', 'ta', 'te', 'kn', 'ml', 'mr', 'bn', 'gu', 'pa', 'or', 'as', name='page_language', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['medical_documents.id'], name=op.f('fk_document_pages_document_id_medical_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['extraction_id'], ['document_extractions.id'], name=op.f('fk_document_pages_extraction_id_document_extractions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], name=op.f('fk_document_pages_patient_id_patient_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_pages')),
    sa.UniqueConstraint('document_id', 'page_number', 'text_sha256', name='uq_document_page_text')
    )
    op.create_index('ix_document_pages_document_current', 'document_pages', ['document_id', 'superseded_at'], unique=False)
    op.create_index(op.f('ix_document_pages_patient_id'), 'document_pages', ['patient_id'], unique=False)
    op.add_column('ai_extracted_facts', sa.Column('evidence_page_number', sa.Integer(), nullable=True))
    op.add_column('ai_extracted_facts', sa.Column('evidence_bbox', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_extracted_facts', 'evidence_bbox')
    op.drop_column('ai_extracted_facts', 'evidence_page_number')
    op.drop_index(op.f('ix_document_pages_patient_id'), table_name='document_pages')
    op.drop_index('ix_document_pages_document_current', table_name='document_pages')
    op.drop_table('document_pages')
    op.drop_index(op.f('ix_document_extractions_patient_id'), table_name='document_extractions')
    op.drop_index(op.f('ix_document_extractions_document_id'), table_name='document_extractions')
    op.drop_table('document_extractions')
    # ### end Alembic commands ###
