"""evidence document reference

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-12 15:54:23.396725
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0005'
down_revision: str | None = '0004'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_extracted_facts', sa.Column('evidence_document_id', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_extracted_facts', 'evidence_document_id')
    # ### end Alembic commands ###
