"""ip-sakti legal source corpus

IP-SAKTI Sahayak Phase 2: the versioned legal and regulatory source corpus and
its curator workflow (D-081–D-086). Seven new tables, and no existing table
touched:

* `instruments` — what a source is a text of (an Act, Rules, a treaty);
* `corpus_documents` — one official source file and its provenance;
* `corpus_pages` — the text read from each page, verbatim;
* `corpus_chunks` — fixed, line-bounded slices of that text, for later search;
* `provisions` — the identity of one provision across its versions;
* `provision_versions` — an exact span of a source's text, as one version;
* `provision_status_events` — append-only, what cited sources say.

Every table carries `lane`, and composite foreign keys on (id, lane) hold a
child to its parent's lane in the database (D-082). Triggers refuse any UPDATE
of an approved or rejected source or version, any change of lane, and any
UPDATE at all of pages, chunks and status events (D-084). They are written out
here rather than imported, so this revision stays what it was when it shipped.

Autogenerated, then edited by hand for the triggers and the downgrade.

Revision ID: ipsakti_0002
Revises: ipsakti_0001
Create Date: 2026-10-01 13:01:05.694421
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'ipsakti_0002'
down_revision: str | None = 'ipsakti_0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_FINAL = "OLD.review_state IN ('approved', 'rejected')"
#: (table, condition under which an UPDATE is refused; None = always)
_IMMUTABLE = (
    ('corpus_documents', f"{_FINAL} OR OLD.lane <> NEW.lane"),
    ('provision_versions', f"{_FINAL} OR OLD.lane <> NEW.lane"),
    ('instruments', "OLD.lane <> NEW.lane"),
    ('provisions', "OLD.lane <> NEW.lane"),
    ('corpus_pages', None),
    ('corpus_chunks', None),
    ('provision_status_events', None),
)
_CORPUS_TABLES = (
    'provision_status_events', 'provision_versions', 'provisions', 'corpus_chunks', 'corpus_pages',
    'corpus_documents', 'instruments',
)


def _create_triggers() -> None:
    dialect = op.get_bind().dialect.name
    if dialect == 'postgresql':
        op.execute(
            """
            CREATE OR REPLACE FUNCTION corpus_refuse_update() RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'corpus record in % is immutable', TG_TABLE_NAME
                    USING ERRCODE = 'integrity_constraint_violation';
            END;
            $$ LANGUAGE plpgsql
            """
        )
    for table, condition in _IMMUTABLE:
        name = f"trg_{table}_immutable"
        if dialect == 'postgresql':
            when = f" WHEN ({condition})" if condition else ""
            op.execute(
                f"CREATE TRIGGER {name} BEFORE UPDATE ON {table} FOR EACH ROW{when} "
                "EXECUTE FUNCTION corpus_refuse_update()"
            )
        elif dialect == 'sqlite':
            when = f" WHEN {condition}" if condition else ""
            op.execute(
                f"CREATE TRIGGER {name} BEFORE UPDATE ON {table} FOR EACH ROW{when} "
                f"BEGIN SELECT RAISE(ABORT, 'corpus record in {table} is immutable'); END"
            )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruments',
    sa.Column('lane', sa.Enum('india', 'international', name='corpus_lane', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('instrument_type', sa.Enum('act', 'rules', 'regulations', 'notification', 'treaty', 'protocol', 'directive', 'other', name='instrument_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('issued_by', sa.String(length=300), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_instruments_created_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instruments')),
    sa.UniqueConstraint('id', 'lane', name='uq_instruments_id_lane'),
    sa.UniqueConstraint('lane', 'instrument_type', 'title', name='uq_instruments_lane_type_title')
    )
    op.create_index(op.f('ix_instruments_lane'), 'instruments', ['lane'], unique=False)
    op.create_table('corpus_documents',
    sa.Column('lane', sa.Enum('india', 'international', name='corpus_lane', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('instrument_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('source_authority', sa.Enum('india_code', 'e_gazette', 'ip_india', 'nba', 'fssai', 'wipo_lex', name='source_authority', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('document_type', sa.Enum('original_text', 'consolidated_text', 'amendment', 'notification', 'other', name='corpus_document_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('source_url', sa.String(length=2000), nullable=True),
    sa.Column('source_reference', sa.String(length=1000), nullable=True),
    sa.Column('source_date', sa.Date(), nullable=True),
    sa.Column('retrieved_on', sa.Date(), nullable=False),
    sa.Column('terms_status', sa.Enum('unknown', 'verified_permitted', 'verified_restricted', name='terms_status', native_enum=False, create_constraint=True, length=32), server_default='unknown', nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_reference', sa.String(length=512), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('ingestion_state', sa.Enum('uploaded', 'parsed', 'needs_review', 'failed', name='ingestion_state', native_enum=False, create_constraint=True, length=32), server_default='uploaded', nullable=False),
    sa.Column('ingestion_issues', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('parse_error_code', sa.String(length=64), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('text_sha256', sa.String(length=64), nullable=True),
    sa.Column('text_length', sa.Integer(), nullable=True),
    sa.Column('extraction_methods', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('extraction_engines', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parsed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('review_state', sa.Enum('draft', 'under_review', 'approved', 'rejected', name='corpus_review_state', native_enum=False, create_constraint=True, length=32), server_default='draft', nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('issues_acknowledged', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("review_state <> 'approved' OR (approved_at IS NOT NULL AND approved_by_user_id IS NOT NULL)", name=op.f('ck_corpus_documents_approval_recorded')),
    sa.CheckConstraint("review_state <> 'rejected' OR (rejected_at IS NOT NULL AND rejected_by_user_id IS NOT NULL)", name=op.f('ck_corpus_documents_rejection_recorded')),
    sa.CheckConstraint("review_state = 'draft' OR ingestion_state IN ('parsed', 'needs_review')", name=op.f('ck_corpus_documents_reviewed_only_when_read')),
    sa.CheckConstraint('source_url IS NOT NULL OR source_reference IS NOT NULL', name=op.f('ck_corpus_documents_provenance_required')),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], name=op.f('fk_corpus_documents_approved_by_user_id_users')),
    sa.ForeignKeyConstraint(['instrument_id', 'lane'], ['instruments.id', 'instruments.lane'], name='fk_corpus_documents_instrument_lane'),
    sa.ForeignKeyConstraint(['parsed_by_user_id'], ['users.id'], name=op.f('fk_corpus_documents_parsed_by_user_id_users')),
    sa.ForeignKeyConstraint(['rejected_by_user_id'], ['users.id'], name=op.f('fk_corpus_documents_rejected_by_user_id_users')),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], name=op.f('fk_corpus_documents_submitted_by_user_id_users')),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], name=op.f('fk_corpus_documents_uploaded_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_corpus_documents')),
    sa.UniqueConstraint('id', 'lane', name='uq_corpus_documents_id_lane')
    )
    op.create_index(op.f('ix_corpus_documents_instrument_id'), 'corpus_documents', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_corpus_documents_lane'), 'corpus_documents', ['lane'], unique=False)
    op.create_index('ix_corpus_documents_lane_review_state', 'corpus_documents', ['lane', 'review_state'], unique=False)
    op.create_index(op.f('ix_corpus_documents_review_state'), 'corpus_documents', ['review_state'], unique=False)
    op.create_index('uq_corpus_documents_live_sha256', 'corpus_documents', ['sha256'], unique=True, postgresql_where=sa.text("review_state <> 'rejected'"), sqlite_where=sa.text("review_state <> 'rejected'"))
    op.create_table('provisions',
    sa.Column('instrument_id', sa.Uuid(), nullable=False),
    sa.Column('lane', sa.Enum('india', 'international', name='corpus_lane', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('locator', sa.String(length=200), nullable=False),
    sa.Column('locator_type', sa.Enum('section', 'subsection', 'clause', 'rule', 'regulation', 'article', 'paragraph', 'schedule', 'item', 'other', name='locator_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_provisions_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['instrument_id', 'lane'], ['instruments.id', 'instruments.lane'], name='fk_provisions_instrument_lane'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provisions')),
    sa.UniqueConstraint('id', 'lane', name='uq_provisions_id_lane')
    )
    op.create_index(op.f('ix_provisions_instrument_id'), 'provisions', ['instrument_id'], unique=False)
    op.create_index('ix_provisions_instrument_locator', 'provisions', ['instrument_id', 'locator'], unique=False)
    op.create_index(op.f('ix_provisions_lane'), 'provisions', ['lane'], unique=False)
    op.create_table('corpus_chunks',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('lane', sa.Enum('india', 'international', name='corpus_lane', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('text_sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('char_end > char_start', name=op.f('ck_corpus_chunks_span_not_empty')),
    sa.ForeignKeyConstraint(['document_id', 'lane'], ['corpus_documents.id', 'corpus_documents.lane'], name='fk_corpus_chunks_document_lane', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_corpus_chunks')),
    sa.UniqueConstraint('document_id', 'ordinal', name='uq_corpus_chunks_document_ordinal')
    )
    op.create_index(op.f('ix_corpus_chunks_document_id'), 'corpus_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_corpus_chunks_lane'), 'corpus_chunks', ['lane'], unique=False)
    op.create_table('corpus_pages',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), server_default='', nullable=False),
    sa.Column('text_sha256', sa.String(length=64), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('engine', sa.String(length=160), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('blocks', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('warnings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['corpus_documents.id'], name=op.f('fk_corpus_pages_document_id_corpus_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_corpus_pages')),
    sa.UniqueConstraint('document_id', 'page_number', name='uq_corpus_pages_document_page')
    )
    op.create_index(op.f('ix_corpus_pages_document_id'), 'corpus_pages', ['document_id'], unique=False)
    op.create_table('provision_versions',
    sa.Column('provision_id', sa.Uuid(), nullable=False),
    sa.Column('lane', sa.Enum('india', 'international', name='corpus_lane', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('text_sha256', sa.String(length=64), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=False),
    sa.Column('page_end', sa.Integer(), nullable=False),
    sa.Column('ocr_derived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('review_state', sa.Enum('draft', 'under_review', 'approved', 'rejected', name='corpus_review_state', native_enum=False, create_constraint=True, length=32), server_default='draft', nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('issues_acknowledged', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("review_state <> 'approved' OR (approved_at IS NOT NULL AND approved_by_user_id IS NOT NULL)", name=op.f('ck_provision_versions_approval_recorded')),
    sa.CheckConstraint("review_state <> 'rejected' OR (rejected_at IS NOT NULL AND rejected_by_user_id IS NOT NULL)", name=op.f('ck_provision_versions_rejection_recorded')),
    sa.CheckConstraint('char_end > char_start', name=op.f('ck_provision_versions_span_not_empty')),
    sa.CheckConstraint('valid_from IS NULL OR valid_to IS NULL OR valid_to >= valid_from', name=op.f('ck_provision_versions_validity_ordered')),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], name=op.f('fk_provision_versions_approved_by_user_id_users')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_provision_versions_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['document_id', 'lane'], ['corpus_documents.id', 'corpus_documents.lane'], name='fk_provision_versions_document_lane'),
    sa.ForeignKeyConstraint(['provision_id', 'lane'], ['provisions.id', 'provisions.lane'], name='fk_provision_versions_provision_lane'),
    sa.ForeignKeyConstraint(['rejected_by_user_id'], ['users.id'], name=op.f('fk_provision_versions_rejected_by_user_id_users')),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], name=op.f('fk_provision_versions_submitted_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provision_versions')),
    sa.UniqueConstraint('id', 'lane', name='uq_provision_versions_id_lane'),
    sa.UniqueConstraint('provision_id', 'version_number', name='uq_provision_versions_number')
    )
    op.create_index(op.f('ix_provision_versions_document_id'), 'provision_versions', ['document_id'], unique=False)
    op.create_index(op.f('ix_provision_versions_lane'), 'provision_versions', ['lane'], unique=False)
    op.create_index(op.f('ix_provision_versions_provision_id'), 'provision_versions', ['provision_id'], unique=False)
    op.create_index(op.f('ix_provision_versions_review_state'), 'provision_versions', ['review_state'], unique=False)
    op.create_index('ix_provision_versions_validity', 'provision_versions', ['valid_from', 'valid_to'], unique=False)
    op.create_table('provision_status_events',
    sa.Column('provision_version_id', sa.Uuid(), nullable=False),
    sa.Column('lane', sa.Enum('india', 'international', name='corpus_lane', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('status', sa.Enum('in_force', 'not_yet_in_force', 'amended', 'superseded', 'stayed', 'omitted', 'disputed', 'withdrawn', name='provision_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('basis_document_id', sa.Uuid(), nullable=True),
    sa.Column('basis_reference', sa.String(length=1000), nullable=True),
    sa.Column('note', sa.String(length=2000), nullable=True),
    sa.Column('recorded_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('basis_document_id IS NOT NULL OR basis_reference IS NOT NULL', name=op.f('ck_provision_status_events_basis_required')),
    sa.ForeignKeyConstraint(['basis_document_id', 'lane'], ['corpus_documents.id', 'corpus_documents.lane'], name='fk_status_events_basis_lane'),
    sa.ForeignKeyConstraint(['provision_version_id', 'lane'], ['provision_versions.id', 'provision_versions.lane'], name='fk_status_events_version_lane'),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], name=op.f('fk_provision_status_events_recorded_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provision_status_events'))
    )
    op.create_index(op.f('ix_provision_status_events_basis_document_id'), 'provision_status_events', ['basis_document_id'], unique=False)
    op.create_index(op.f('ix_provision_status_events_lane'), 'provision_status_events', ['lane'], unique=False)
    op.create_index('ix_provision_status_events_version_recorded', 'provision_status_events', ['provision_version_id', 'recorded_at'], unique=False)
    # ### end Alembic commands ###
    _create_triggers()


def downgrade() -> None:
    # Curators' work and approved legal text live only here (the source files
    # stay in storage, but which were approved, and what was cut from them, does
    # not). Dropping it as a side effect of a schema change is refused, as 0009
    # and ipsakti_0001 refuse; empty the corpus deliberately first.
    bind = op.get_bind()
    counts = {
        table: bind.execute(sa.text(f"SELECT COUNT(*) FROM {table}")).scalar()
        for table in ('instruments', 'corpus_documents')
    }
    if any(counts.values()):
        raise RuntimeError(
            "Refusing to downgrade ipsakti_0002: the legal source corpus is not empty "
            f"({counts['instruments']} instrument(s), {counts['corpus_documents']} source document(s)). "
            "Nothing has been changed."
        )
    for table in _CORPUS_TABLES:
        on = f" ON {table}" if bind.dialect.name == 'postgresql' else ""
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table}_immutable{on}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_provision_status_events_version_recorded', table_name='provision_status_events')
    op.drop_index(op.f('ix_provision_status_events_lane'), table_name='provision_status_events')
    op.drop_index(op.f('ix_provision_status_events_basis_document_id'), table_name='provision_status_events')
    op.drop_table('provision_status_events')
    op.drop_index('ix_provision_versions_validity', table_name='provision_versions')
    op.drop_index(op.f('ix_provision_versions_review_state'), table_name='provision_versions')
    op.drop_index(op.f('ix_provision_versions_provision_id'), table_name='provision_versions')
    op.drop_index(op.f('ix_provision_versions_lane'), table_name='provision_versions')
    op.drop_index(op.f('ix_provision_versions_document_id'), table_name='provision_versions')
    op.drop_table('provision_versions')
    op.drop_index(op.f('ix_corpus_pages_document_id'), table_name='corpus_pages')
    op.drop_table('corpus_pages')
    op.drop_index(op.f('ix_corpus_chunks_lane'), table_name='corpus_chunks')
    op.drop_index(op.f('ix_corpus_chunks_document_id'), table_name='corpus_chunks')
    op.drop_table('corpus_chunks')
    op.drop_index(op.f('ix_provisions_lane'), table_name='provisions')
    op.drop_index('ix_provisions_instrument_locator', table_name='provisions')
    op.drop_index(op.f('ix_provisions_instrument_id'), table_name='provisions')
    op.drop_table('provisions')
    op.drop_index('uq_corpus_documents_live_sha256', table_name='corpus_documents', postgresql_where=sa.text("review_state <> 'rejected'"), sqlite_where=sa.text("review_state <> 'rejected'"))
    op.drop_index(op.f('ix_corpus_documents_review_state'), table_name='corpus_documents')
    op.drop_index('ix_corpus_documents_lane_review_state', table_name='corpus_documents')
    op.drop_index(op.f('ix_corpus_documents_lane'), table_name='corpus_documents')
    op.drop_index(op.f('ix_corpus_documents_instrument_id'), table_name='corpus_documents')
    op.drop_table('corpus_documents')
    op.drop_index(op.f('ix_instruments_lane'), table_name='instruments')
    op.drop_table('instruments')
    # ### end Alembic commands ###
    if bind.dialect.name == 'postgresql':
        op.execute('DROP FUNCTION IF EXISTS corpus_refuse_update()')
