"""ip-sakti product profiles and classifier

IP-SAKTI Sahayak Phase 3: a user's product profiles and the formulation
classifier's sessions (D-087–D-091). Five new tables; no existing table is
touched, and none references a healthcare table:

* `product_profiles` — what a user says their product is; their facts only;
* `classification_sessions` — one walk of one tree version for one product;
* `classification_answers` — append-only; a revision supersedes, never edits;
* `classification_outcomes` — each result reached, written once; a category
  only when determined, by CHECK;
* `classifier_reference_links` — a curator's link from a reference slot to an
  approved provision version, held to its lane by a composite foreign key.

Triggers refuse any UPDATE of outcomes and reference links, of a confirmed,
rejected or superseded session, and of a superseded answer or an answer's
choice. They are written out here, not imported, so this revision stays what
it was when it shipped.

Autogenerated, then edited by hand for the triggers and the downgrade.

Revision ID: ipsakti_0003
Revises: ipsakti_0002
Create Date: 2026-10-01 16:20:00.000000
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'ipsakti_0003'
down_revision: str | None = 'ipsakti_0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: (table, condition under which an UPDATE is refused; None = always)
_FINAL = (
    ('classification_outcomes', None),
    ('classifier_reference_links', None),
    ('classification_sessions', "OLD.status IN ('user_confirmed', 'user_rejected', 'superseded')"),
    (
        'classification_answers',
        "OLD.superseded_at IS NOT NULL OR NEW.choice <> OLD.choice OR NEW.node_id <> OLD.node_id "
        "OR NEW.session_id <> OLD.session_id",
    ),
)


def _create_triggers() -> None:
    dialect = op.get_bind().dialect.name
    if dialect == 'postgresql':
        op.execute(
            """
            CREATE OR REPLACE FUNCTION sakti_refuse_final_update() RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'record in % is final and cannot be changed', TG_TABLE_NAME
                    USING ERRCODE = 'integrity_constraint_violation';
            END;
            $$ LANGUAGE plpgsql
            """
        )
    for table, condition in _FINAL:
        name = f"trg_{table}_final"
        if dialect == 'postgresql':
            when = f" WHEN ({condition})" if condition else ""
            op.execute(
                f"CREATE TRIGGER {name} BEFORE UPDATE ON {table} FOR EACH ROW{when} "
                "EXECUTE FUNCTION sakti_refuse_final_update()"
            )
        elif dialect == 'sqlite':
            when = f" WHEN {condition}" if condition else ""
            op.execute(
                f"CREATE TRIGGER {name} BEFORE UPDATE ON {table} FOR EACH ROW{when} "
                f"BEGIN SELECT RAISE(ABORT, 'record in {table} is final and cannot be changed'); END"
            )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_profiles',
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('intended_use', sa.String(length=2000), nullable=True),
    sa.Column('dosage_form', sa.String(length=200), nullable=True),
    sa.Column('administration_route', sa.Enum('oral', 'topical', 'nasal', 'parenteral', 'other', 'unknown', name='administration_route', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('ingredients', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('preparation_method', sa.String(length=5000), nullable=True),
    sa.Column('classical_reference', sa.String(length=300), nullable=True),
    sa.Column('extract_description', sa.String(length=2000), nullable=True),
    sa.Column('standardization_description', sa.String(length=2000), nullable=True),
    sa.Column('markers', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('text_language', sa.Enum('en', 'hi', 'ta', 'te', 'kn', 'ml', 'mr', 'bn', 'gu', 'pa', 'or', 'as', name='product_text_language', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_product_profiles_owner_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_profiles'))
    )
    op.create_index(op.f('ix_product_profiles_owner_user_id'), 'product_profiles', ['owner_user_id'], unique=False)
    op.create_table('classification_sessions',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('classifier_id', sa.String(length=64), nullable=False),
    sa.Column('tree_version', sa.Integer(), nullable=False),
    sa.Column('tree_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('incomplete', 'requires_information', 'determined', 'user_confirmed', 'user_rejected', 'superseded', name='classification_status', native_enum=False, create_constraint=True, length=32), server_default='incomplete', nullable=False),
    sa.Column('current_node_id', sa.String(length=64), nullable=True),
    sa.Column('product_revision', sa.Integer(), nullable=False),
    sa.Column('product_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('restarted_from_id', sa.Uuid(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('decided_outcome_id', sa.Uuid(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=1000), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status NOT IN ('user_confirmed', 'user_rejected') OR (decided_at IS NOT NULL AND decided_by_user_id IS NOT NULL AND decided_outcome_id IS NOT NULL)", name=op.f('ck_classification_sessions_decision_recorded')),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], name=op.f('fk_classification_sessions_decided_by_user_id_users')),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_classification_sessions_owner_user_id_users')),
    sa.ForeignKeyConstraint(['product_id'], ['product_profiles.id'], name=op.f('fk_classification_sessions_product_id_product_profiles')),
    sa.ForeignKeyConstraint(['restarted_from_id'], ['classification_sessions.id'], name='fk_classification_sessions_restarted_from'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_classification_sessions'))
    )
    op.create_index(op.f('ix_classification_sessions_owner_user_id'), 'classification_sessions', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_classification_sessions_product_id'), 'classification_sessions', ['product_id'], unique=False)
    op.create_index(op.f('ix_classification_sessions_status'), 'classification_sessions', ['status'], unique=False)
    op.create_index('uq_classification_sessions_one_open', 'classification_sessions', ['product_id'], unique=True, postgresql_where=sa.text("status IN ('incomplete', 'requires_information', 'determined')"), sqlite_where=sa.text("status IN ('incomplete', 'requires_information', 'determined')"))
    op.create_table('classification_answers',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.String(length=64), nullable=False),
    sa.Column('choice', sa.String(length=64), nullable=False),
    sa.Column('answered_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['answered_by_user_id'], ['users.id'], name=op.f('fk_classification_answers_answered_by_user_id_users')),
    sa.ForeignKeyConstraint(['session_id'], ['classification_sessions.id'], name=op.f('fk_classification_answers_session_id_classification_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_classification_answers'))
    )
    op.create_index(op.f('ix_classification_answers_session_id'), 'classification_answers', ['session_id'], unique=False)
    op.create_index('uq_classification_answers_current', 'classification_answers', ['session_id', 'node_id'], unique=True, postgresql_where=sa.text('superseded_at IS NULL'), sqlite_where=sa.text('superseded_at IS NULL'))
    op.create_table('classification_outcomes',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('determined', 'requires_information', name='outcome_kind', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('category', sa.Enum('classical', 'patent_proprietary', 'new_or_non_classical', 'phytopharmaceutical', 'ayurveda_aahara', 'cosmetic', name='formulation_category', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('stop_node_id', sa.String(length=64), nullable=True),
    sa.Column('path', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('answers_sha256', sa.String(length=64), nullable=False),
    sa.Column('tree_version', sa.Integer(), nullable=False),
    sa.Column('tree_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('references', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("(kind = 'determined' AND category IS NOT NULL AND stop_node_id IS NULL) OR (kind = 'requires_information' AND category IS NULL AND stop_node_id IS NOT NULL)", name=op.f('ck_classification_outcomes_category_only_when_determined')),
    sa.ForeignKeyConstraint(['session_id'], ['classification_sessions.id'], name=op.f('fk_classification_outcomes_session_id_classification_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_classification_outcomes')),
    sa.UniqueConstraint('session_id', 'sequence', name='uq_classification_outcomes_sequence')
    )
    op.create_index(op.f('ix_classification_outcomes_category'), 'classification_outcomes', ['category'], unique=False)
    op.create_index(op.f('ix_classification_outcomes_session_id'), 'classification_outcomes', ['session_id'], unique=False)
    op.create_table('classifier_reference_links',
    sa.Column('classifier_id', sa.String(length=64), nullable=False),
    sa.Column('tree_version', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.String(length=64), nullable=False),
    sa.Column('provision_version_id', sa.Uuid(), nullable=False),
    sa.Column('lane', sa.Enum('india', 'international', name='corpus_lane', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('linked_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['linked_by_user_id'], ['users.id'], name=op.f('fk_classifier_reference_links_linked_by_user_id_users')),
    sa.ForeignKeyConstraint(['provision_version_id', 'lane'], ['provision_versions.id', 'provision_versions.lane'], name='fk_classifier_reference_links_version_lane'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_classifier_reference_links'))
    )
    op.create_index(op.f('ix_classifier_reference_links_provision_version_id'), 'classifier_reference_links', ['provision_version_id'], unique=False)
    op.create_index('ix_classifier_reference_links_slot', 'classifier_reference_links', ['classifier_id', 'tree_version', 'slot_id', 'created_at'], unique=False)
    # ### end Alembic commands ###
    _create_triggers()


def downgrade() -> None:
    # Product profiles and classifications are what users wrote and decided.
    # Dropping them as a side effect of a schema change is refused, as 0009,
    # ipsakti_0001 and ipsakti_0002 refuse; remove them deliberately first.
    bind = op.get_bind()
    counts = {
        table: bind.execute(sa.text(f"SELECT COUNT(*) FROM {table}")).scalar()
        for table in ('product_profiles', 'classifier_reference_links')
    }
    if any(counts.values()):
        raise RuntimeError(
            "Refusing to downgrade ipsakti_0003: "
            f"{counts['product_profiles']} product profile(s) and "
            f"{counts['classifier_reference_links']} classifier reference link(s) exist. Nothing has been changed."
        )
    for table, _ in _FINAL:
        on = f" ON {table}" if bind.dialect.name == 'postgresql' else ""
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table}_final{on}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_classifier_reference_links_slot', table_name='classifier_reference_links')
    op.drop_index(op.f('ix_classifier_reference_links_provision_version_id'), table_name='classifier_reference_links')
    op.drop_table('classifier_reference_links')
    op.drop_index(op.f('ix_classification_outcomes_session_id'), table_name='classification_outcomes')
    op.drop_index(op.f('ix_classification_outcomes_category'), table_name='classification_outcomes')
    op.drop_table('classification_outcomes')
    op.drop_index('uq_classification_answers_current', table_name='classification_answers', postgresql_where=sa.text('superseded_at IS NULL'), sqlite_where=sa.text('superseded_at IS NULL'))
    op.drop_index(op.f('ix_classification_answers_session_id'), table_name='classification_answers')
    op.drop_table('classification_answers')
    op.drop_index('uq_classification_sessions_one_open', table_name='classification_sessions', postgresql_where=sa.text("status IN ('incomplete', 'requires_information', 'determined')"), sqlite_where=sa.text("status IN ('incomplete', 'requires_information', 'determined')"))
    op.drop_index(op.f('ix_classification_sessions_status'), table_name='classification_sessions')
    op.drop_index(op.f('ix_classification_sessions_product_id'), table_name='classification_sessions')
    op.drop_index(op.f('ix_classification_sessions_owner_user_id'), table_name='classification_sessions')
    op.drop_table('classification_sessions')
    op.drop_index(op.f('ix_product_profiles_owner_user_id'), table_name='product_profiles')
    op.drop_table('product_profiles')
    # ### end Alembic commands ###
    if bind.dialect.name == 'postgresql':
        op.execute('DROP FUNCTION IF EXISTS sakti_refuse_final_update()')
