from abc import ABC, abstractmethod


class StorageError(Exception):
    pass


class ObjectNotFound(StorageError):
    pass


class ObjectStorageProvider(ABC):
    """Minimal object-storage contract. Local disk now; S3/MinIO later.

    `key` is always generated by the application (never from user input).
    The returned `storage_reference` is opaque to callers.
    """

    name: str

    @abstractmethod
    def put(self, key: str, data: bytes, content_type: str) -> str: ...

    @abstractmethod
    def get(self, reference: str) -> bytes: ...

    @abstractmethod
    def delete(self, reference: str) -> None: ...

    @abstractmethod
    def exists(self, reference: str) -> bool: ...
